import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "@/Components/Navbar";
import Header from "@/Components/Header";
import Navbar2 from "@/Components/Navbar2";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <Navbar2 />
            {children}
         </body>
      </html>
   );
}
