import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Navbar = () => {
   return (
      <nav className="sticky w-full bg-red-800 h-16">
         <ul className="flex justify-center">
            <li>Home</li>
            <li>About</li>
            <li>Services</li>
         </ul>
      </nav>
   );
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <Navbar />
            {children}
         </body>
      </html>
   );
}
