import './globals.css'
import { Inter } from "next/font/google";
import Navbar2 from "@/Components/Navbar2";
import Navbar from "@/Components/Navbar";
import Navbar3 from "@/Components/Navbar3";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "Tailwind CSS",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <Navbar2 />
            {children}
         </body>
      </html>
   );
}
